// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using VoxEvents.API.Entities;

namespace VoxEvents.API.Migrations
{
    [DbContext(typeof(VoxEventsContext))]
    partial class VoxEventsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VoxEvents.API.Entities.Availability", b =>
                {
                    b.Property<int>("MemberId");

                    b.Property<int>("VoxEventId");

                    b.Property<bool>("Available");

                    b.HasKey("MemberId", "VoxEventId");

                    b.HasIndex("VoxEventId");

                    b.ToTable("Availabilities");
                });

            modelBuilder.Entity("VoxEvents.API.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("Part");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("VoxEvents.API.Entities.VoxEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EventDate");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("EventVenue")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("PerformanceTime");

                    b.Property<DateTime>("RehearsalTime");

                    b.HasKey("Id");

                    b.ToTable("VoxEvents");
                });

            modelBuilder.Entity("VoxEvents.API.Entities.Availability", b =>
                {
                    b.HasOne("VoxEvents.API.Entities.Member", "Member")
                        .WithMany("Availabilities")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VoxEvents.API.Entities.VoxEvent", "VoxEvent")
                        .WithMany("Availabilities")
                        .HasForeignKey("VoxEventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
